# Generated by Django 4.2 on 2025-02-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department'),
        ('inventory', '0003_rooms_incharge_alter_activity_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
