# Generated by Django 4.2 on 2025-03-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemgroup_itemgroupitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroupitem',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
