# Generated by Django 4.2 on 2025-02-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department'),
        ('inventory', '0005_activity_user_issues_created_by_purchase_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
