# Generated by Django 4.2 on 2025-03-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itemgroupitem_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_tab', models.BooleanField(default=True)),
                ('item_groups_tab', models.BooleanField(default=True)),
                ('systems_tab', models.BooleanField(default=True)),
                ('categories_tab', models.BooleanField(default=True)),
                ('brands_tab', models.BooleanField(default=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.room')),
            ],
        ),
    ]
