# Generated by Django 4.2 on 2025-02-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=255)),
                ('component_type', models.CharField(choices=[('mouse', 'Mouse'), ('keyboard', 'Keyboard'), ('monitor', 'Monitor'), ('cpu', 'CPU'), ('ups', 'UPS'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('projector', 'Projector'), ('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('server', 'Server'), ('storage', 'Storage'), ('network', 'Network'), ('other', 'Other')], max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.system')),
            ],
            options={
                'unique_together': {('system', 'component_type', 'serial_number')},
            },
        ),
    ]
