# Generated by Django 4.2 on 2025-02-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_systemcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance'), ('disposed', 'Disposed')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
