# Generated by Django 4.2 on 2025-02-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_systemcomponent_component_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='achived_count',
            field=models.IntegerField(default=0),
        ),
    ]
