# Generated by Django 4.2 on 2025-02-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='item_name',
        ),
    ]
