# Generated by Django 4.2 on 2025-02-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_purchase_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='category',
        ),
    ]
