# Generated by Django 4.2 on 2025-02-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_purchase_brand_remove_purchase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
