# Generated by Django 4.2 on 2025-02-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_item_is_listed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(upload_to='receipts/')),
                ('remarks', models.TextField()),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='inventory.purchase')),
            ],
        ),
    ]
