# Generated by Django 4.2 on 2025-02-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_purchasecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='added_to_stock',
            field=models.BooleanField(default=False),
        ),
    ]
