# Generated by Django 4.2 on 2025-02-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_is_institution_admin_and_more'),
        ('inventory', '0018_receipt_delete_purchasecompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_reg_no', models.CharField(max_length=255)),
                ('student_admission_no', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.room')),
            ],
        ),
    ]
