# Generated by Django 4.2 on 2025-02-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_studentissuereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentIssueReport',
        ),
    ]
