# Generated by Django 4.2 on 2025-02-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_vendor_email'),
        ('inventory', '0020_delete_studentissuereport'),
    ]

    operations = [
    ]
