# Generated by Django 4.2 on 2024-06-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_department'),
        ('lab', '0002_alter_lab_dept'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
