# Generated by Django 4.2 on 2024-05-10 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.org'),
            preserve_default=False,
        ),
    ]
