# Generated by Django 4.2 on 2024-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_org_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_lab_staff',
            field=models.BooleanField(default=False, verbose_name='is lab staff'),
        ),
    ]
