# Generated by Django 4.2 on 2024-05-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='incharge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.userprofile'),
        ),
    ]
