# Generated by Django 4.2 on 2024-06-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('org_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(max_length=255)),
                ('website_url', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
