# Generated by Django 4.2 on 2024-05-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=5, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('total_qty', models.IntegerField(default=1)),
                ('in_use_qty', models.IntegerField(default=0)),
                ('total_available_qty', models.IntegerField(default=0)),
                ('removed_qty', models.IntegerField(default=0)),
                ('unit_of_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date_of_purchase', models.DateField()),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.category')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=255)),
                ('room_no', models.IntegerField(unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.org')),
                ('user', models.ManyToManyField(to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=5, unique=True)),
                ('sys_name', models.CharField(max_length=255, verbose_name='System Name')),
                ('status', models.CharField(choices=[('working', 'Working'), ('not_working', 'Not working'), ('item_missing', 'Item missing')], max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cpu_cabin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_cabin', to='lab.item', verbose_name='CPU Cabin')),
                ('hdd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdd', to='lab.item', verbose_name='Hard Disk Drive')),
                ('keyboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyboard', to='lab.item', verbose_name='Keyboard')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor', to='lab.item', verbose_name='Monitor')),
                ('mouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouse', to='lab.item', verbose_name='Mouse')),
                ('os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os', to='lab.item', verbose_name='Operating System')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor', to='lab.item', verbose_name='Processor')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram', to='lab.item', verbose_name='RAM')),
            ],
        ),
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_tab', models.BooleanField(default=False)),
                ('sys_tab', models.BooleanField(default=False)),
                ('categories_tab', models.BooleanField(default=False)),
                ('brands_tab', models.BooleanField(default=False)),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
        migrations.CreateModel(
            name='LabRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.CharField(max_length=500)),
                ('user_desc', models.TextField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab'),
        ),
        migrations.AddField(
            model_name='category',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab'),
        ),
        migrations.AddField(
            model_name='brand',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.lab'),
        ),
    ]
