# Generated by Django 4.2 on 2024-05-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_is_lab_staff'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.org'),
            preserve_default=False,
        ),
    ]
