# Generated by Django 4.2 on 2024-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='removed_qty',
            field=models.IntegerField(default=0),
        ),
    ]
