# Generated by Django 4.2 on 2024-06-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_department'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.department'),
        ),
    ]
