# Generated by Django 4.2 on 2024-05-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_tab', models.BooleanField(default=True)),
                ('sys_tab', models.BooleanField(default=True)),
                ('categories_tab', models.BooleanField(default=True)),
                ('brands_tab', models.BooleanField(default=True)),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
    ]
