# Generated by Django 4.2 on 2024-05-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupItem',
        ),
    ]
