# Generated by Django 4.2 on 2024-06-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_lab_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='cpu_cabin',
        ),
        migrations.RemoveField(
            model_name='system',
            name='hdd',
        ),
        migrations.RemoveField(
            model_name='system',
            name='keyboard',
        ),
        migrations.RemoveField(
            model_name='system',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='system',
            name='mouse',
        ),
        migrations.RemoveField(
            model_name='system',
            name='os',
        ),
        migrations.RemoveField(
            model_name='system',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='system',
            name='ram',
        ),
        migrations.AddField(
            model_name='system',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('mouse', 'Mouse'), ('keyboard', 'Keyboard'), ('processor', 'Processor'), ('ram', 'RAM'), ('storage', 'HDD/SSD'), ('os', 'Operating System'), ('monitor', 'Monitor'), ('cpu_cabin', 'CPU Cabin')], max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.item')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.system')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='components',
            field=models.ManyToManyField(related_name='systems', through='lab.SystemComponent', to='lab.item'),
        ),
    ]
