# Generated by Django 4.2 on 2024-04-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_rename_qty_item_total_qty_groupitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.group'),
        ),
    ]
