# Generated by Django 4.2 on 2024-05-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsettings',
            name='brands_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='categories_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='items_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='sys_tab',
            field=models.BooleanField(default=False),
        ),
    ]
