# Generated by Django 4.2 on 2024-05-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_item_removed_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.CharField(max_length=500)),
                ('user_desc', models.TextField(blank=True, null=True)),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
    ]
