# Generated by Django 4.2 on 2024-05-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_item_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('hdd', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('monitor', models.CharField(max_length=255)),
                ('keyboard', models.CharField(max_length=255)),
                ('cpu_cabin', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='date_created',
            new_name='created_on',
        ),
    ]
