# Generated by Django 4.2 on 2024-05-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_labrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='cpu_cabin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_cabin', to='lab.item'),
        ),
        migrations.AlterField(
            model_name='system',
            name='hdd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdd', to='lab.item'),
        ),
        migrations.AlterField(
            model_name='system',
            name='keyboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyboard', to='lab.item'),
        ),
        migrations.AlterField(
            model_name='system',
            name='monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor', to='lab.item'),
        ),
        migrations.AlterField(
            model_name='system',
            name='mouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouse', to='lab.item'),
        ),
        migrations.AlterField(
            model_name='system',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os', to='lab.item'),
        ),
        migrations.AlterField(
            model_name='system',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor', to='lab.item'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram', to='lab.item'),
        ),
    ]
