# Generated by Django 4.2 on 2024-04-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_groupitem_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
    ]
