# Generated by Django 4.2 on 2024-05-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_system_rename_date_created_item_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.category'),
        ),
    ]
