# Generated by Django 4.2 on 2024-05-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_system_cpu_cabin_alter_system_hdd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrecord',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab'),
        ),
    ]
