# Generated by Django 4.2 on 2024-05-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_labrecord_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor', to='lab.item', verbose_name='Processor'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram', to='lab.item', verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='system',
            name='sys_name',
            field=models.CharField(max_length=255, verbose_name='System Name'),
        ),
    ]
