# Generated by Django 4.2 on 2024-05-15 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_system_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.category'),
        ),
    ]
