# Generated by Django 4.2 on 2024-05-15 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_system_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lab.lab'),
            preserve_default=False,
        ),
    ]
