# Generated by Django 4.2 on 2024-05-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_system_processor_alter_system_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='hdd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdd', to='lab.item', verbose_name='Hard Disk Drive'),
        ),
    ]
