# Generated by Django 4.2 on 2024-07-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_remove_system_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcomponent',
            name='component_type',
            field=models.CharField(choices=[('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Processor', 'Processor'), ('RAM', 'RAM'), ('Storage', 'Storage'), ('OS', 'OS'), ('Monitor', 'Monitor'), ('CPU Cabin', 'CPU Cabin')], max_length=255),
        ),
    ]
