# Generated by Django 4.2 on 2024-05-16 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_category_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='category',
        ),
        migrations.AddField(
            model_name='lab',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
