# Generated by Django 4.2 on 2024-05-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_remove_system_category_lab_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='mouse',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
