# Generated by Django 4.2 on 2024-07-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_itemrecord_remove_item_date_of_purchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRemovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Depreciation', 'Depreciation'), ('Consumption', 'Consumption')], max_length=255)),
                ('qty', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.item')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemRecord',
        ),
    ]
