# Generated by Django 4.2 on 2024-08-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_dept_delete_department'),
        ('lab', '0012_alter_labsettings_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='user',
            field=models.ManyToManyField(related_name='assistants', to='core.userprofile'),
        ),
    ]
