# Generated by Django 4.2 on 2024-08-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='decline',
            field=models.BooleanField(default=False),
        ),
    ]
