# Generated by Django 4.2 on 2024-08-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_decline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='decline',
            new_name='declined',
        ),
    ]
