# Generated by Django 4.2 on 2024-10-05 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_rename_itemremovalrecord_archive'),
        ('purchases', '0003_rename_decline_purchase_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='lab.item'),
        ),
    ]
