# Generated by Django 4.2 on 2024-08-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.org'),
        ),
    ]
