# Generated by Django 4.2 on 2025-02-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_institution_admin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_incharge',
            field=models.BooleanField(default=False, verbose_name='is room incharge'),
        ),
    ]
