# Generated by Django 4.2 on 2024-08-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
