# Generated by Django 4.2 on 2024-08-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('lab', '0002_item_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='org.org'),
            preserve_default=False,
        ),
    ]
