# Generated by Django 4.2 on 2024-08-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('lab', '0003_item_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org.org'),
        ),
    ]
