# Generated by Django 4.2 on 2024-08-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_itemadditionalinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemRemovalRecord',
            new_name='Archive',
        ),
    ]
